### ISSUE TITLE
AttributeError: module 'builtins' has no attribute '__xonsh_shell__'

### ISSUE THREAD

**Issue by gilch** [t184256/xontrib-prompt-vi-mode#1]
This xontrib doesn't seem to work with the latest xonsh (0.8.5) and ptk (2.0.7). The state variable must have been moved somewhere else.

**Comment by t184256** [comment]
Indeed it did, thanks for reporting it.
